/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formulaire;

import FClasse.Stagiaire;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Nissi
 */
public class formListing extends javax.swing.JPanel {

    /**
     * Creates new form formListing
     */
    Stagiaire stag = new Stagiaire();
    public formListing() throws SQLException {
        initComponents();
        stag.Afficher(grille2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        grille2 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtRech = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 51, 81));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        grille2.setBackground(new java.awt.Color(0, 102, 102));
        grille2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        grille2.setForeground(new java.awt.Color(255, 255, 255));
        grille2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(grille2);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 940, 420));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Listing des Stagiaires");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        txtRech.setToolTipText("Recherche par Nom");
        txtRech.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 204), 1, true));
        txtRech.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtRechCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtRechInputMethodTextChanged(evt);
            }
        });
        txtRech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRechActionPerformed(evt);
            }
        });
        add(txtRech, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 190, 30));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Recherche");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, -1, -1, 30));

        jButton1.setIcon(new javax.swing.ImageIcon("D:\\GestionStagiaire\\icon\\icons8_printer_48px_1.png")); // NOI18N
        jButton1.setText("Imprimer");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 140, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void txtRechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRechActionPerformed

    private void txtRechInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtRechInputMethodTextChanged
       
    }//GEN-LAST:event_txtRechInputMethodTextChanged

    private void txtRechCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtRechCaretPositionChanged
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            grille2.repaint();
            stag.Afficher1(grille2, txtRech.getText());
        } catch (SQLException ex) {
            Logger.getLogger(formListing.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txtRechCaretPositionChanged

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
         try {
            // TODO add your handling code here:
            grille2.repaint();
            stag.Afficher1(grille2, txtRech.getText());
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            Class.forName("com.mysql.jdbc.Driver");
            String url="jdbc:mysql://localhost:3306/gestionstagiairebd";
            Connection con = DriverManager.getConnection(url,"root", "");
            JasperReport jr = JasperCompileManager.compileReport("D:\\GestionStagiaire\\src\\FRapport\\report1.jrxml");
            JasperPrint Jp = JasperFillManager.fillReport(jr, null, con);
            JasperViewer.viewReport(Jp);
        } catch (ClassNotFoundException | SQLException | JRException ex) {
            Logger.getLogger(formListing.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable grille2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtRech;
    // End of variables declaration//GEN-END:variables
}
